### ISSUE TITLE
mod isnt being detected

### ISSUE THREAD

**Issue by peow** [ix0rai/ramel#1]
im using the newest version (ramel 0.1.0+mc1.20.2) on Fabric 1.20.1, but the mod isnt being detected, it doesnt show on ModMenu, and doesnt has any effect on the camels, i tested with the old version but also didnt work
![2024-01-30_12 38 34](https://github.com/ix0rai/ramel/assets/105888751/000022a4-d229-4bc1-874e-98b4f1d4eb9e)

if possible pls make an update with support to fabric loader 0.14.22

**Comment by eristhea** [comment]
can you send your game log?

**Comment by peow** [comment]
[latest.log](https://github.com/ix0rai/ramel/files/14100835/latest.log)

**Comment by eristhea** [comment]
the mod is for sure in your mods folder?

**Comment by peow** [comment]
modrinth launcher
![image](https://github.com/ix0rai/ramel/assets/105888751/0ffb8ce5-c30a-4ecf-bcf1-0aae10f682c2)

mods folder
![image](https://github.com/ix0rai/ramel/assets/105888751/bc9e6424-b7b0-4e3d-aa60-240d9593a1b6)

**Comment by eristhea** [comment]
interesting, thanks for letting me know!
I'll test
