### ISSUE TITLE
crashes server on 1.20.6 after jumping 

### ISSUE THREAD

**Issue by nickademas** [ix0rai/ramel#3]
[crash-2024-05-29_17.30.47-server.txt](https://github.com/ix0rai/ramel/files/15486706/crash-2024-05-29_17.30.47-server.txt)
[latest.log](https://github.com/ix0rai/ramel/files/15486707/latest.log)

**Comment by eristhea** [comment]
the version was mistakenly marked compatible with 1.20.6 when it only works on 1.20.4. I'll release a fix tonight (~4-5 hours)

**Comment by eristhea** [comment]
versions 1.0.0 through 1.0.2 are no longer marked as compatible with 1.20.6. I'll release a version compatible with .6 as well as a version with corrected metadata for .4.
