### ISSUE TITLE
game crashes immediately upon camel charge

### ISSUE THREAD

**Issue by 6xolotl** [ix0rai/ramel#5]
exit code: -1

specific error message:
> The game crashed whilst ticking entity
> Error: java.lang.NoSuchFieldError: Class net.minecraft.class_1294 does not have member field 'net.minecraft.class_1291 field_5904'

crash log:
[latest.log](https://github.com/user-attachments/files/15511168/latest.log)

ive already tried removing all of my other mods, and even on its own it still crashes the game ;-;

**Comment by orifu** [comment]
thanks for the report! this bug was (hopefully) fixed in 1.0.3, so could you try that and see if it works?

**Comment by 6xolotl** [comment]
looks to be fixed, thank you!!
